"""Add model_version

Revision ID: 2b80b82c9194
Revises: 0005_legal_guardian
Create Date: 2026-07-21 21:42:33.599959+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b80b82c9194'
down_revision: Union[str, None] = '0005_legal_guardian'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voiceprints', sa.Column('model_version', sa.String(length=50), server_default='ecapa-voxceleb', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voiceprints', 'model_version')
    # ### end Alembic commands ###
